# -*- coding: utf-8 -*-
"""Hudace daily batch content data. Region-agnostic. SAP-calm voice:
no emojis, no em dashes, no exclamation. Outcome first, method second."""

RUN_DATE = "2026-06-21"
INDUSTRIES = ["Retail", "Education and Research"]

DEPLOY_BASE = "https://leadloftexporter.vercel.app/email"

BRAND = {
    "bg":     "#0A0919",
    "bg2":    "#08080f",
    "bg3":    "#05050D",
    "white":  "#ffffff",
    "muted":  "#9A9AAE",
    "accent": "#1B90FF",
}

CONTACT = {
    "phone_display": "+91 82189 29990",
    "phone_raw":     "918218929990",
    "email":         "contact@hudace.com",
    "site":          "hudace.com",
    "wa":            "https://wa.me/918218929990",
    "website":       "https://hudace.com",
    "instagram":     "https://www.instagram.com/hudaceofficial/",
    "linkedin":      "https://www.linkedin.com/company/hudace",
}

# Each service: a full deliverables-first email plus message variants.
SERVICES = [
    {
        "slug": "social-media",
        "name": "Social Media",
        "industry": "Retail",
        "headline": "SOCIAL",
        "subhead": "A full social presence, produced and managed every month.",
        "queries": ["dark cinematic studio neon", "moody product photography dark", "cinematic city night neon"],
        "deliverables": [
            "6 short-form videos per month",
            "12 feed posts per month",
            "8 stories per month",
            "Captions and hashtag sets",
            "Content calendar and scheduling",
            "Community management, comments and DMs",
            "Monthly performance report",
        ],
        "scope": "For retail, this means a steady feed that mirrors your shelves and seasons, so every drop, offer and restock reaches buyers where they already scroll.",
        "proof": "In retail and consumer brands we have turned scattered posting into one calendar and one voice, and watched saved posts and profile visits compound into store and site traffic.",
        "future": "As the account matures we layer in paid amplification and shoppable formats, so the same content begins to sell directly.",
        "hooks": [
            ("Consistency beats bursts", "Twelve posts and six videos a month keep you in the feed every week, so buyers see you the day they are ready to spend, not weeks late."),
            ("Managed, not just made", "Comments and DMs are answered for you, so interest turns into orders instead of cooling off in an unread inbox."),
            ("Decisions from the report", "The monthly report shows what drove reach and saves, so next month is built on evidence, not guesswork."),
        ],
        "closing": "Hand us the calendar and the inbox. You get a social channel that runs itself and reports back.",
    },
    {
        "slug": "seo-aeo-geo-srx",
        "name": "SEO AEO GEO SRX",
        "industry": "Retail",
        "headline": "FOUND",
        "subhead": "Rank in search, and inside AI answers, before your competitors.",
        "queries": ["dark data network abstract", "cinematic dark technology blue", "search abstract dark blue"],
        "deliverables": [
            "Technical SEO audit and fixes",
            "Keyword and intent research",
            "On-page optimization, titles, meta, headings, schema",
            "Content briefs and optimization",
            "Authority and backlink building",
            "Local SEO, profile, citations, maps",
            "AEO, answer-engine optimization, FAQ and structured answers",
            "GEO, visibility inside AI-generated answers",
            "SRX, search experience and Core Web Vitals",
            "Monthly ranking and traffic report",
        ],
        "scope": "For retail, this puts your categories and best sellers in front of buyers at the exact moment they search, and inside the AI answers they now ask first.",
        "proof": "In retail and services we have rebuilt site structure and intent coverage so the right pages surface for the right queries, and qualified traffic grows month over month.",
        "future": "Once rankings hold we extend into AEO and GEO so your brand is the answer assistants quote, not the link they skip.",
        "hooks": [
            ("Intent, not just keywords", "We map what buyers actually want, so the pages that rank are the pages that convert, not vanity traffic."),
            ("Visible inside AI answers", "GEO and AEO place you where buyers now look first, so you are cited while competitors wait for clicks that no longer come."),
            ("Speed that holds rankings", "SRX and Core Web Vitals work keeps pages fast, so you keep the positions you earn instead of losing them to slow load times."),
        ],
        "closing": "We make you the result search returns and the answer AI gives. Both, every month.",
    },
    {
        "slug": "website-design",
        "name": "Website Design",
        "industry": "Retail",
        "headline": "LAUNCH",
        "subhead": "A fast, mobile-first website you can edit yourself.",
        "queries": ["dark modern interior architecture", "cinematic dark workspace laptop", "dark minimal architecture night"],
        "deliverables": [
            "Custom multi-page website",
            "Mobile-first responsive build",
            "Booking, lead, and contact forms",
            "CMS to edit content yourself",
            "SEO-ready structure and speed",
            "Analytics and WhatsApp integration",
            "Hosting and domain setup",
            "Launch and handover",
        ],
        "scope": "For retail, this is a storefront that loads fast on the phone, captures the enquiry, and routes it straight to WhatsApp so no buyer waits.",
        "proof": "In retail and consumer brands we have replaced slow, hard-to-edit sites with fast builds the team controls, and watched bounce fall and enquiries rise.",
        "future": "The same foundation extends into full commerce and booking flows when you are ready to sell and schedule online.",
        "hooks": [
            ("Built for the thumb", "A mobile-first build means the majority of buyers, who arrive on a phone, get a site that loads and converts, not one that fights them."),
            ("You hold the keys", "The CMS lets your team change prices, offers and pages in minutes, so the site stays current without a developer in the loop."),
            ("Enquiry to WhatsApp", "Forms and WhatsApp are wired in, so every lead lands in a chat you already watch, and follow-up happens while intent is hot."),
        ],
        "closing": "We design it, build it, host it, and hand it over. You run it from your phone.",
    },
    {
        "slug": "erp-building",
        "name": "ERP Building",
        "industry": "Education and Research",
        "headline": "SYSTEM",
        "subhead": "Custom business software, built around how you actually work.",
        "queries": ["dark server data center blue", "cinematic dark control room", "abstract dark network nodes blue"],
        "deliverables": [
            "Discovery and module blueprint",
            "Custom modules, CRM, inventory, billing, HR, and more",
            "Role-based access and dashboards",
            "Workflow automations",
            "Integrations, payments, messaging, APIs",
            "Web and mobile access",
            "Training and documentation",
            "Ongoing support and iterations",
        ],
        "scope": "For education and research, this replaces spreadsheets and disconnected tools with one system for records, billing, staff and reporting, accessible on web and mobile.",
        "proof": "Across institutions and services we have unified fragmented data into one operating system, so leaders see one real-time view instead of reconciling reports by hand.",
        "future": "Each module ships, then iterates, so the system grows with you instead of forcing a rebuild every time a process changes.",
        "hooks": [
            ("Built around your workflow", "Custom modules fit how you already operate, so staff adopt the system instead of fighting software designed for someone else."),
            ("One view for leaders", "Role-based dashboards put the numbers that matter in one place, so decisions come from live data, not week-old exports."),
            ("Automations remove the busywork", "Workflows handle the repetitive steps, so your people spend their hours on judgement, not on re-entering the same data twice."),
        ],
        "closing": "We map it, build it, and keep iterating. You get software that runs your operation, not the other way around.",
    },
    {
        "slug": "ai-work-studio",
        "name": "AI Work Studio",
        "industry": "Retail",
        "headline": "CINEMA",
        "subhead": "A cinematic film and a month of cuts, in seven days, no film crew.",
        "queries": ["cinematic film dark moody lighting", "dark cinematic portrait spotlight", "cinematic dark abstract light"],
        "deliverables": [
            "60-second cinematic film",
            "Three 15-second social cuts",
            "Ten AI-generated stills",
            "Script and concept included",
            "Delivered in seven working days, no film crew",
        ],
        "scope": "For retail, this gives you a hero film for the launch and three cuts for social, so one production feeds the campaign, the feed and the storefront.",
        "proof": "Across consumer brands we have produced cinematic work without crews or shoot days, so the cost and the wait that used to block premium video simply disappear.",
        "future": "Once the look is set we can produce on a recurring cadence, so every campaign and season has fresh film without a new shoot.",
        "hooks": [
            ("Premium without the crew", "AI production removes the shoot day, so you get cinematic quality at a fraction of the cost and none of the scheduling."),
            ("One film, many cuts", "The 60-second film plus three social cuts means one concept covers the whole campaign, so nothing is left underfed."),
            ("Seven days, not seven weeks", "Delivery in a working week means your launch keeps its date, so the content is ready when the moment is, not after it passes."),
        ],
        "closing": "Give us the brief. In seven days you have the film, the cuts and the stills, ready to ship.",
    },
    {
        "slug": "schoolos",
        "name": "SchoolOS School ERP",
        "industry": "Education and Research",
        "headline": "SCHOOL",
        "subhead": "Run the whole institution on one AI-native platform.",
        "queries": ["dark cinematic library architecture", "modern school dark cinematic", "dark campus architecture night"],
        "deliverables": [
            "Admissions, online enquiry to enrollment",
            "Student records, profiles, documents, history",
            "Attendance, daily and period, parent alerts",
            "Fees, invoices, online payments, reminders, receipts",
            "Examinations, marks, grading, report cards",
            "Timetable, classes, teachers, substitutions",
            "Communication, announcements and parent app",
            "Transport, routes, vehicles, live tracking",
            "Library, catalog, issue and return",
            "HR and payroll, staff and salaries",
            "Reports, management dashboards",
        ],
        "scope": "For education and research, this connects admissions, academics, fees and communication on one platform, with AI handling the admin so staff stay with students.",
        "proof": "Across institutions we have moved admissions to alumni onto one system, so leaders get one real-time view and parents get one app instead of a dozen messages.",
        "future": "The platform scales from a single campus to a group, so growth adds branches to the same system rather than new silos.",
        "hooks": [
            ("One platform, every process", "Admissions, attendance, fees and exams live in one place, so staff stop stitching together tools and start working from one source of truth."),
            ("Parents in one app", "Alerts, fees and announcements reach parents in a single app, so communication is consistent and the office stops fielding the same questions."),
            ("Leaders see it live", "Management dashboards show enrollment, fees and attendance in real time, so decisions are made on today's numbers, not last term's."),
        ],
        "closing": "Admissions to alumni, fees to transport, on one AI-native platform. We set it up and train your team.",
    },
]
