# -*- coding: utf-8 -*-
"""Hudace daily batch content. Industries: Retail (A), Construction and Real Estate (B).
SAP tone: calm, authoritative, outcome-first. No emojis, no em dashes, no exclamation.
Region-agnostic. Real services and SchoolOS modules from hudace.com."""

EMAILS = [
    # 1. Service into Industry A: Social Media Marketing for Retail
    {
        "key": "retail-social",
        "title": "Retail | Social Media Marketing",
        "label": "Social Media Marketing for Retail",
        "headline": "Social that moves stock",
        "subhead": "Retail-grade social content and paid distribution, produced on a fixed monthly cadence and measured against revenue.",
        "deliver_label": "What We Deliver",
        "deliverables": [
            "16 feed posts and 12 short-form reels every month, planned around your promotions and seasons",
            "20 stories per month with shoppable links to priority categories",
            "2 paid social campaigns per month, built, launched, and optimised against return on ad spend",
            "A content calendar approved one week ahead, plus a monthly performance report tied to sales",
        ],
        "scope_label": "The Scope In Retail",
        "scope": "Retail demand is won in the feed before it is won in the aisle or the cart. We run your social presence as a managed function. Catalogue-aware creative, a posting cadence that matches your trading calendar, and paid distribution that puts the right product in front of the right buyer at the moment intent is highest.",
        "hooks": [
            ("Cadence beats bursts", "A fixed weekly rhythm keeps your brand in feed all month, so demand compounds instead of spiking once and fading."),
            ("Creative tied to catalogue", "Every post maps to a category you want to move, so attention turns into add to cart rather than passive reach."),
            ("Paid and organic on one plan", "Organic proves the message, paid scales the winners, and budget follows what already converts."),
        ],
        "proof": "In a consumer retail mandate, a disciplined content cadence paired with paid distribution lifted digital conversion threefold against the prior quarter.",
        "future": "As the account matures we layer in lifecycle retargeting, user-generated content programmes, and seasonal launch playbooks, so each quarter starts from a proven base rather than a blank calendar.",
        "hero_query": "retail fashion store interior dark",
        "body_query": "shopping smartphone mobile",
        "card_deliverables": ["16 posts and 12 reels per month", "20 shoppable stories per month", "2 paid campaigns per month", "Calendar and revenue report"],
    },
    # 2. Service into Industry B: AI Cinematic Videos for Real Estate
    {
        "key": "realestate-aivideo",
        "title": "Construction and Real Estate | AI Cinematic Videos",
        "label": "AI Cinematic Videos for Real Estate",
        "headline": "Sell the space before it is built",
        "subhead": "Cinematic property films and AI-generated walkthroughs, delivered on a predictable schedule for every launch and listing.",
        "deliver_label": "What We Deliver",
        "deliverables": [
            "4 cinematic property films per month, each in a 60 second hero cut plus 15 and 30 second paid cuts",
            "8 AI-generated walkthroughs or fly-throughs per month for pre-construction and active listings",
            "12 vertical reels per month formatted for social and broker channels",
            "Master files, captions, and aspect-ratio variants delivered within five working days of shoot or brief",
        ],
        "scope_label": "The Scope In Real Estate",
        "scope": "Buyers and investors decide on a property long before a site visit. We produce cinematic films and AI-generated walkthroughs that present a development at its best, from pre-construction render to finished asset, so your sales team opens conversations with conviction rather than a brochure.",
        "hooks": [
            ("Show the unbuilt", "AI walkthroughs let you market a development before completion, so sales begin while the asset is still rising."),
            ("One shoot, many cuts", "Every film ships in hero, paid, and vertical cuts, so a single production feeds the website, ads, and broker channels."),
            ("Cinematic signals quality", "Production value reads as asset quality, which lifts perceived value and shortens the path to a serious enquiry."),
        ],
        "proof": "For a real estate developer, cinematic launch films and walkthroughs carried a pre-construction release and filled the enquiry pipeline ahead of completion.",
        "future": "We extend into full launch systems, drone and interior capture libraries, and AI-personalised investor reels, so every new phase has a ready cinematic pipeline.",
        "hero_query": "luxury modern architecture night building",
        "body_query": "real estate apartment interior",
        "card_deliverables": ["4 cinematic films per month", "8 AI walkthroughs per month", "12 vertical reels per month", "Delivery in 5 working days"],
    },
    # 3. Industry A, multiple services: Retail
    {
        "key": "retail-growth",
        "title": "Retail | Growth Infrastructure",
        "label": "Growth Infrastructure for Retail",
        "headline": "One growth engine for retail",
        "subhead": "Search, social, web, and paid run as one accountable system, reported on revenue rather than reach.",
        "deliver_label": "Services Mapped To Outcomes",
        "deliverables": [
            "Social Media Marketing, a managed posting and paid cadence that keeps priority categories in feed and moving",
            "Performance Marketing, full-funnel search and paid social attributed to revenue, not impressions",
            "Website Development, a conversion-architected storefront built for speed and checkout completion",
            "Search Engine Optimisation, category and product visibility across classic and AI-driven search",
        ],
        "scope_label": "The Pressure On Retail",
        "scope": "Retail margins are pressured from every side. Acquisition costs rise, attention fragments across channels, and discounting erodes the bottom line. The answer is not more activity. It is connected infrastructure where search, social, website, and paid media work from one plan and one source of truth.",
        "hooks": [
            ("Channels stop competing", "When social, search, and paid share one plan, budget flows to what converts instead of to whichever team shouts loudest."),
            ("Attributed to revenue", "Every channel reports against sales, so you fund outcomes and retire activity that only produces reach."),
            ("Built for the trading calendar", "The whole system plans around your seasons and promotions, so peak periods are prepared rather than improvised."),
        ],
        "proof": "A multi-market retail brand unified fragmented data and declining conversion into one performance system and tripled digital conversion.",
        "future": None,
        "hero_query": "shopping mall retail dark modern",
        "body_query": "retail analytics dashboard data",
        "card_deliverables": ["Social cadence and paid", "Performance marketing", "Conversion website", "SEO and AEO"],
    },
    # 4. Industry B, multiple services: Construction and Real Estate
    {
        "key": "realestate-growth",
        "title": "Construction and Real Estate | Growth Infrastructure",
        "label": "Growth Infrastructure for Real Estate",
        "headline": "Pipeline for every project",
        "subhead": "Cinematic content, conversion sites, and paid demand built as one system for developers and brokers.",
        "deliver_label": "Services Mapped To Outcomes",
        "deliverables": [
            "AI Cinematic Videos, launch films and walkthroughs that present each asset at its best from pre-construction",
            "Website Development, fast project microsites built to capture and qualify enquiries",
            "Performance Marketing, targeted demand to investors and buyers with full attribution to enquiries",
            "Search Engine Optimisation, durable visibility for projects and locations across search and AI answers",
        ],
        "scope_label": "The Pressure On Real Estate",
        "scope": "Real estate sells on confidence and timing. Long sales cycles, high-value decisions, and crowded listings mean a development has to look credible and reach the right buyer at the right moment. Disconnected agencies cannot deliver that. One integrated growth system can.",
        "hooks": [
            ("Confidence is the conversion", "Cinematic presentation and a credible site signal asset quality, which is what turns a browser into a serious enquiry."),
            ("Reach the rare buyer", "Targeted paid media finds the small pool of qualified investors, so spend is not wasted on volume that never transacts."),
            ("One system per launch", "Content, site, and demand ship together for every phase, so launches stop being assembled from scratch each time."),
        ],
        "proof": "A real estate developer ran a pre-construction launch on connected cinematic content and targeted demand, filling the enquiry pipeline before completion.",
        "future": None,
        "hero_query": "modern skyscraper construction night city",
        "body_query": "architecture building blueprint",
        "card_deliverables": ["Cinematic launch films", "Project microsites", "Targeted paid demand", "Project and location SEO"],
    },
    # 5. AI Work Studio
    {
        "key": "ai-work-studio",
        "title": "AI Work Studio",
        "label": "Hudace AI Work Studio",
        "headline": "A studio that never sleeps",
        "subhead": "AI cinematic videos, photography, cinematic ads, and AI films, produced at a pace and price traditional studios cannot match.",
        "deliver_label": "What The Studio Produces",
        "deliverables": [
            "AI cinematic videos and short films from script to final cut, on a monthly production slate",
            "AI photography and product imagery, unlimited concepts without a physical shoot",
            "Cinematic ad creative built in multiple cuts and aspect ratios for every channel",
            "Brand-consistent output, drafts in days rather than weeks, with revisions handled in the same cycle",
        ],
        "scope_label": "Why A Studio On Demand",
        "scope": "Traditional production is slow and expensive, and it does not scale to the volume modern channels demand. The AI Work Studio produces cinematic videos, photography, ads, and AI films on an industrial cadence, so you can test more ideas, ship more creative, and keep every channel fed without a production bottleneck.",
        "hooks": [
            ("Volume without the shoot", "AI production removes the cost and lead time of crews and locations, so more concepts reach the market."),
            ("Test, then scale", "Cheap, fast variants let the audience pick the winner before budget commits, which lowers the cost of being right."),
            ("On brand, every time", "A trained brand system keeps tone and look consistent across hundreds of assets, so scale does not dilute the brand."),
        ],
        "proof": "Brands that moved creative onto an AI production slate shipped more variants per campaign and found winning creative faster than a traditional studio cycle allows.",
        "future": "The studio grows with you, from a steady content slate to full campaign worlds, AI-personalised creative, and a reusable brand asset library.",
        "hero_query": "cinematic film camera production dark",
        "body_query": "video editing studio screen",
        "card_deliverables": ["AI cinematic videos and films", "AI photography, no shoot", "Cinematic ads, all formats", "Drafts in days"],
    },
    # 6. Market research
    {
        "key": "market-opportunity",
        "title": "Market Opportunity Briefing",
        "label": "Market Opportunity Briefing",
        "headline": "Where the demand is moving",
        "subhead": "A read on where buyer attention, AI search, and content economics are heading, and what it means for your growth plan.",
        "deliver_label": "What The Signals Show",
        "deliverables": [
            "Search is splitting into classic results and AI answers, so visibility now requires optimising for both, AEO and GEO alongside SEO",
            "Short-form and cinematic video drive the majority of consideration, which rewards brands that can produce at volume",
            "AI production has collapsed the cost of creative, so output is now a strategy choice rather than a budget limit",
            "Buyers reward integrated brands, where content, search, and site tell one coherent story end to end",
        ],
        "scope_label": "The Shifts Reshaping Growth",
        "scope": "Three shifts are reshaping how growth is won. Buyers now begin journeys inside AI answers rather than a list of links. Video has become the default format for consideration, not an optional extra. And the economics of content have changed, because AI production removes the cost that once capped how much a brand could ship. The organisations that adjust their infrastructure to these shifts capture demand that competitors cannot see.",
        "hooks": [
            ("Visibility is being redefined", "As answers replace links, the brands structured for AI search inherit the traffic the rest are about to lose."),
            ("Format is the moat", "When video carries consideration, the ability to produce cinematic content at volume becomes a durable advantage."),
            ("Cost is no longer the cap", "Once AI removes production cost, the limit on growth is ambition and infrastructure, not budget."),
        ],
        "proof": "Across mandates spanning financial services, healthcare, energy, and real estate, organisations that consolidated growth onto one accountable system measured conversion gains their fragmented competitors could not.",
        "future": "The practical next step is an audit of where you stand on AI search readiness, content velocity, and channel integration, then a roadmap that closes the gaps in priority order.",
        "hero_query": "city skyline night business lights",
        "body_query": "data analytics chart dark screen",
        "card_deliverables": ["AI search is the new front door", "Video carries consideration", "AI collapses content cost", "Integration wins the buyer"],
    },
    # 7. School ERP
    {
        "key": "schoolos",
        "title": "Hudace SchoolOS | School ERP",
        "label": "Hudace SchoolOS",
        "headline": "Run the whole school as one",
        "subhead": "An AI-native platform that connects admissions to alumni, with Nectar AI handling the busywork so staff focus on students.",
        "deliver_label": "Modules And How Each Is Used",
        "deliverables": [
            "Student Information, the daily record for management, attendance, timetable, curriculum, examinations, library, transport, and hostel",
            "Admissions, an enquiry-to-enrolment funnel where Nectar follows up so more interest becomes enrolment",
            "Finance, fee management, invoicing, and reconciliation with clean records and fewer overdue accounts",
            "LMS and People Management, connected learning for students and faculty and HR administration for staff",
        ],
        "scope_label": "Why One Platform",
        "scope": "Most institutions run on disconnected tools, where admissions, academics, finance, and communication never share one record. Hudace SchoolOS brings every process onto a single platform, with Xenon AI working in the background, so leaders get one real-time view and teams spend less time on admin and more time with students.",
        "hooks": [
            ("One source of truth", "When admissions, academics, and finance share one record, leaders see the whole institution in real time instead of stitching reports."),
            ("AI takes the busywork", "Nectar automates routine admin across attendance, fees, and follow-ups, which returns staff time to teaching."),
            ("Live in weeks, not terms", "Accelerated deployment means the platform is running this term, with measurable outcomes from the start."),
        ],
        "proof": "Institutions running on a connected platform report up to sixty percent less time on routine administration and more enquiries converting to enrolment.",
        "future": "From a single campus to a multi-campus group, SchoolOS scales to one real-time view across every site, with accreditation reporting generated on demand.",
        "hero_query": "school campus building students",
        "body_query": "classroom students learning bright",
        "card_deliverables": ["Student Information and exams", "Admissions with Nectar AI", "Fee and finance management", "LMS, HR, live in weeks"],
    },
]
