"""Shared data for the Hudace daily content batch."""

RUN_DATE = "2026-07-19"
INDUSTRIES = ["Retail", "Professional Services"]

BRAND = {
    "bg": "#0A0919",
    "bg2": "#08080f",
    "bg3": "#05050D",
    "text": "#FFFFFF",
    "muted": "#9A9AAE",
    "accent": "#1B90FF",
}

CONTACT = {
    "phone_display": "+91 82189 29990",
    "phone_e164": "918218929990",
    "email": "contact@hudace.com",
    "site": "hudace.com",
    "wa": "https://wa.me/918218929990",
    "web": "https://hudace.com",
    "instagram": "https://www.instagram.com/hudaceofficial/",
    "linkedin": "https://www.linkedin.com/company/hudace",
}

# Deployed image host (per routine). Images are committed to public/email/.
IMG_BASE = "https://leadloftexporter.vercel.app/email"

# Each service -> canonical deliverables (verbatim from the routine brief).
SERVICES = [
    {
        "key": "social-media",
        "name": "Social Media",
        "hero_word": "Social that performs",
        "sub": "Six videos, twelve posts, one measurement framework. Every month.",
        "subject": "Social Media",
        "card_headline": "Social media that moves the number",
        "photo_query": "dark cinematic city night neon",
        "deliverables": [
            "6 short-form videos / month",
            "12 feed posts / month",
            "8 stories / month",
            "Captions and hashtag sets",
            "Content calendar and scheduling",
            "Community management (comments and DMs)",
            "Monthly performance report",
        ],
        "scope": "Built for a retail brand that needs consistent presence across feed, stories, and short-form, without a scramble every week.",
        "proof": "In retail, a steady content cadence tied to a measurement framework is what turns a following into repeat purchase, not reach for its own sake.",
        "future": "As the account grows, the same calendar extends into paid amplification and community programs without rebuilding from scratch.",
        "closing": "Book a short call and we will map your first month of content this week.",
        "hooks": [
            ("A cadence you can trust", "Six videos and twelve posts every month means your brand never goes quiet, so buyers see you when they are ready."),
            ("Reported against outcomes", "A monthly performance report ties content to what matters, not to impressions alone."),
            ("Community handled", "Comments and DMs answered means demand is captured the moment it appears, not the next morning."),
        ],
    },
    {
        "key": "seo",
        "name": "SEO / AEO / GEO / SRX",
        "hero_word": "Found first",
        "sub": "Ranked in search, cited in AI answers, fast on every device.",
        "subject": "SEO / AEO / GEO / SRX",
        "card_headline": "Ranked in search. Cited by AI.",
        "photo_query": "dark data analytics screen blue",
        "deliverables": [
            "Technical SEO audit and fixes",
            "Keyword and intent research",
            "On-page optimization (titles, meta, headings, schema)",
            "Content briefs and optimization",
            "Authority and backlink building",
            "Local SEO (profile, citations, maps)",
            "AEO: answer-engine optimization (FAQ, structured answers)",
            "GEO: visibility inside AI-generated answers",
            "SRX: search experience and Core Web Vitals",
            "Monthly ranking and traffic report",
        ],
        "scope": "Built for a professional services firm whose buyers research before they ever fill in a form.",
        "proof": "In professional services, being the answer a buyer finds first, in search and inside AI answers, is what shortens a long consideration cycle.",
        "future": "The same foundation compounds. Rankings and answer-engine visibility built this quarter keep returning traffic long after the work is done.",
        "closing": "Request an audit and we will show you where you rank and where you should.",
        "hooks": [
            ("Visibility where buyers look now", "AEO and GEO put you inside AI-generated answers, not only the blue links, so you are found however people search."),
            ("Intent, not just keywords", "Keyword and intent research means you rank for terms that convert, not vanity volume."),
            ("Experience that holds the click", "SRX and Core Web Vitals work keeps the visit fast, so hard-won rankings turn into enquiries."),
        ],
    },
    {
        "key": "website-design",
        "name": "Website Design",
        "hero_word": "A site that sells",
        "sub": "Custom, mobile-first, and built to turn visits into enquiries.",
        "subject": "Website Design",
        "card_headline": "A website built to convert",
        "photo_query": "dark laptop workspace night blue",
        "deliverables": [
            "Custom multi-page website",
            "Mobile-first responsive build",
            "Booking, lead, and contact forms",
            "CMS to edit content yourself",
            "SEO-ready structure and speed",
            "Analytics and WhatsApp integration",
            "Hosting and domain setup",
            "Launch and handover",
        ],
        "scope": "Built for a retail brand that needs a storefront online as considered as the one in the aisle.",
        "proof": "In retail, a mobile-first site with fast pages and clear paths to buy is what keeps a click from becoming a bounce.",
        "future": "The CMS handover means the site grows with you. New pages, offers, and campaigns ship without a developer in the loop.",
        "closing": "Send us your current site and we will map the rebuild.",
        "hooks": [
            ("Built for the buyer journey", "A custom, SEO-ready structure guides visitors from landing to enquiry, not a template that fights you."),
            ("Yours to run", "A CMS and full handover means you edit content and launch offers yourself, no ticket queue."),
            ("Enquiries wired in", "Booking, lead forms, and WhatsApp integration route interest straight to you the moment it lands."),
        ],
    },
    {
        "key": "erp-building",
        "name": "ERP Building",
        "hero_word": "Software that fits",
        "sub": "Custom business software built around how you actually work.",
        "subject": "ERP Building (Custom Software / SaaS)",
        "card_headline": "Custom software, built around you",
        "photo_query": "dark server data center blue technology",
        "deliverables": [
            "Discovery and module blueprint",
            "Custom modules (CRM, inventory, billing, HR, and more)",
            "Role-based access and dashboards",
            "Workflow automations",
            "Integrations (payments, messaging, APIs)",
            "Web and mobile access",
            "Training and documentation",
            "Ongoing support and iterations",
        ],
        "scope": "Built for a professional services firm outgrowing spreadsheets and disconnected tools.",
        "proof": "In professional services, software shaped to your workflow, not off-the-shelf compromise, is what removes the manual work that slows delivery.",
        "future": "The blueprint is modular. Start with the workflow that hurts most, then add CRM, billing, and HR as the system proves itself.",
        "closing": "Book a discovery call and we will blueprint your first module.",
        "hooks": [
            ("Shaped to your process", "A discovery-led module blueprint means the software fits how you work, so adoption is immediate."),
            ("Automation where it counts", "Workflow automations remove the repetitive admin that quietly consumes billable hours."),
            ("One source of truth", "Role-based dashboards and integrations replace scattered spreadsheets with a single real-time view."),
        ],
    },
    {
        "key": "ai-work-studio",
        "name": "AI Work Studio",
        "hero_word": "Cinematic, no crew",
        "sub": "A sixty-second film and a month of cuts, delivered in seven days.",
        "subject": "AI Work Studio (Cinematic Video)",
        "card_headline": "Cinematic film. No crew. Seven days.",
        "photo_query": "dark cinematic film lighting studio",
        "deliverables": [
            "60-second cinematic film",
            "Three 15-second social cuts",
            "Ten AI-generated stills",
            "Script and concept included",
            "Delivered in seven working days, no film crew",
        ],
        "scope": "Built for a retail brand that needs premium film for a launch without a production budget or a shoot schedule.",
        "proof": "In retail, cinematic film shot the traditional way takes weeks and a crew. AI Work Studio delivers the same premium look in seven working days.",
        "future": "One concept becomes a library. The film, the cuts, and the stills feed feed, ads, and stories for the whole campaign.",
        "closing": "Share your product and we will send back a concept and script.",
        "hooks": [
            ("Premium without the shoot", "A sixty-second cinematic film with no film crew means launch-grade video without the launch-grade budget."),
            ("One shoot, many cuts", "Three social cuts and ten stills from one concept feed every channel at once."),
            ("Fast enough to matter", "Seven working days means the film is ready for the moment, not after it has passed."),
        ],
    },
    {
        "key": "schoolos",
        "name": "SchoolOS (School ERP)",
        "hero_word": "One platform, whole school",
        "sub": "Admissions to alumni on a single AI-native system.",
        "subject": "SchoolOS (School ERP)",
        "card_headline": "Run the whole school on one platform",
        "photo_query": "dark modern school library architecture",
        "deliverables": [
            "Admissions: online enquiry to enrollment",
            "Student records: profiles, documents, history",
            "Attendance: daily and period, parent alerts",
            "Fees: invoices, online payments, reminders, receipts",
            "Examinations: marks, grading, report cards",
            "Timetable: classes, teachers, substitutions",
            "Communication: announcements and parent app",
            "Transport: routes, vehicles, live tracking",
            "Library: catalog, issue and return",
            "HR and payroll: staff and salaries",
            "Reports: management dashboards",
        ],
        "scope": "Built for an institution running admissions, academics, finance, and communication across separate tools.",
        "proof": "Institutions that consolidate onto one AI-native platform report far less time lost to routine administration and one real-time view across the school.",
        "future": "SchoolOS goes live in weeks, not terms, and its AI keeps records clean and surfaces what needs attention as you grow.",
        "closing": "Book a walkthrough and we will show SchoolOS on your own workflow.",
        "hooks": [
            ("Admissions to alumni, unified", "One platform across admissions, academics, finance, and communication replaces the tool sprawl that slows a school down."),
            ("Less routine admin", "AI handles attendance, fee reminders, and record-keeping, freeing staff for students."),
            ("Parents in the loop", "A parent app with alerts and announcements keeps families informed without adding to the front-office load."),
        ],
    },
]
