"use client";

/**
 * WhatsApp Outreach — multi-account bulk sender via WhatsApp Web pairing.
 *
 * Flow:
 *  1. Connect one or more WhatsApp numbers by scanning the QR with the phone's
 *     "Linked Devices" — the QR is generated by Baileys server-side and
 *     streamed back as a base64 data URL.
 *  2. Build a campaign: pick a connected account, paste a message with
 *     {first_name}/{company}/{full_name}/{title}/{email} tokens, choose
 *     recipients from either (a) a pipeline stage or (b) selected lead IDs.
 *  3. Server resolves the lead rows → contacts and hands them to the Node
 *     sidecar which sends with a randomised inter-message delay.
 *
 * Backend routes (proxied through FastAPI to the Node sidecar):
 *   /whatsapp-web/accounts          — list/add/delete/status
 *   /whatsapp-web/campaigns/start   — start a bulk run
 *   /whatsapp-web/campaigns         — list runs + live progress
 */

import { useEffect, useRef, useState } from "react";
import { useSearchParams } from "next/navigation";
import {
  useQuery,
  useMutation,
  useQueryClient,
} from "@tanstack/react-query";
import {
  MessageCircle,
  Plus,
  RefreshCcw,
  LogOut,
  Loader2,
  Smartphone,
  Send,
  CheckCircle2,
  AlertCircle,
  Users,
  Play,
  Pause,
  Paperclip,
  X,
  Inbox as InboxIcon,
  FolderOpen,
} from "lucide-react";
import { api, ApiError } from "@/lib/api";
import type { PipelineStage } from "@/lib/types";

// Read a File into a raw base64 string (no data: prefix) for the JSON API.
function fileToBase64(file: File): Promise<string> {
  return new Promise((resolve, reject) => {
    const r = new FileReader();
    r.onload = () => {
      const s = String(r.result || "");
      resolve(s.includes(",") ? s.split(",")[1] : s);
    };
    r.onerror = reject;
    r.readAsDataURL(file);
  });
}

interface WaChat {
  jid: string;
  phone: string;
  name: string;
  lastMessage: string;
  lastMessageTime: number;
  fromMe: boolean;
  unreadCount: number;
}

interface WaMessage {
  id: string;
  phone: string;
  fromMe: boolean;
  sender: string;
  text: string;
  timestamp: number;
  type: string;
}

interface WaAccount {
  id: string;
  label: string;
  createdAt: number;
  status: "ready" | "qr" | "connecting" | "disconnected";
  qrDataUrl: string | null;
  phone: string | null;
  pushName: string | null;
}

interface WaCampaignStats {
  total: number;
  processed: number;
  sent: number;
  failed: number;
}

interface WaCampaign {
  id: string;
  accountId: string | null;
  message: string;
  status: "queued" | "running" | "paused" | "completed" | "cancelled" | "failed";
  stats: WaCampaignStats;
  results: { phone: string; name: string; result: string | null }[];
  createdAt: number;
  startedAt: number | null;
  completedAt: number | null;
}

interface LeadLite {
  id: string;
  full_name: string | null;
  phone: string | null;
}

const STATUS_BADGE: Record<string, { bg: string; text: string; label: string }> = {
  ready:        { bg: "#dcfce7", text: "#166534", label: "Connected" },
  qr:           { bg: "#fef3c7", text: "#92400e", label: "Scan QR" },
  connecting:   { bg: "#e0e7ff", text: "#3730a3", label: "Connecting…" },
  disconnected: { bg: "#fee2e2", text: "#991b1b", label: "Disconnected" },
};

const CAMP_BADGE: Record<string, { bg: string; text: string }> = {
  queued:    { bg: "#e0e7ff", text: "#3730a3" },
  running:   { bg: "#fef3c7", text: "#92400e" },
  paused:    { bg: "#e1e3e4", text: "#414942" },
  completed: { bg: "#dcfce7", text: "#166534" },
  cancelled: { bg: "#fee2e2", text: "#991b1b" },
  failed:    { bg: "#fee2e2", text: "#991b1b" },
};

export default function WhatsAppOutreachPage() {
  const qc = useQueryClient();

  // ── Accounts ──────────────────────────────────────────────────────────
  const { data: accounts = [], error: accountsError } = useQuery<WaAccount[]>({
    queryKey: ["wa-accounts"],
    queryFn: () => api("/whatsapp-web/accounts"),
    refetchInterval: 3000, // poll so the QR refreshes + status flips on pair
  });

  // Any sidecar failure (not configured = 503, host down = 404/502, gateway
  // errors) means QR pairing can't work — surface the diagnostic banner rather
  // than the misleading "click Add number" empty state.
  const sidecarUnavailable =
    accountsError instanceof ApiError && [404, 500, 502, 503].includes(accountsError.status);
  const sidecarErrorDetail =
    accountsError instanceof ApiError ? accountsError.message : "";

  const addAccount = useMutation({
    mutationFn: (label: string) =>
      api("/whatsapp-web/accounts", { method: "POST", body: { label } }),
    onSuccess: () => qc.invalidateQueries({ queryKey: ["wa-accounts"] }),
    onError: (e) =>
      alert(
        e instanceof ApiError
          ? `Couldn't start pairing: ${e.message}\n\nThe WhatsApp sidecar service must be deployed and reachable.`
          : "Couldn't start pairing — the WhatsApp service is unavailable."
      ),
  });

  const reconnect = useMutation({
    mutationFn: (id: string) =>
      api(`/whatsapp-web/accounts/${id}/reconnect`, { method: "POST" }),
    onSuccess: () => qc.invalidateQueries({ queryKey: ["wa-accounts"] }),
  });

  const logout = useMutation({
    mutationFn: (id: string) =>
      api(`/whatsapp-web/accounts/${id}/logout`, { method: "POST" }),
    onSuccess: () => qc.invalidateQueries({ queryKey: ["wa-accounts"] }),
  });

  const removeAccount = useMutation({
    mutationFn: (id: string) =>
      api(`/whatsapp-web/accounts/${id}`, { method: "DELETE" }),
    onSuccess: () => qc.invalidateQueries({ queryKey: ["wa-accounts"] }),
  });

  // ── Composer state ────────────────────────────────────────────────────
  const [accountId, setAccountId] = useState<string>("");
  const [message, setMessage] = useState<string>("Hi {first_name}, ");
  const [stageId, setStageId] = useState<string>("");
  const [countryCode, setCountryCode] = useState<string>("91");
  const [delayMin, setDelayMin] = useState<number>(5);
  const [delayMax, setDelayMax] = useState<number>(12);
  const [lastRunNotice, setLastRunNotice] = useState<string>("");
  // Optional media attached to every message in the bulk send (the personalised
  // text becomes the caption — e.g. product photo + "{first_name}, …").
  const [media, setMedia] = useState<{ base64: string; mimetype: string; filename: string } | null>(null);

  // ── Pre-fill from a Content Hub whatsapp asset ────────────────────────
  // /whatsapp?from_asset=<id> — the "Send on WhatsApp" button on a Content
  // Hub WhatsApp asset lands here. Fetch the asset and seed the composer
  // message once; every field stays editable and the user attaches a product
  // image + picks recipients here.
  const searchParams = useSearchParams();
  const fromAssetId = searchParams.get("from_asset") || "";
  const [assetNotice, setAssetNotice] = useState<string>("");
  const prefilledRef = useRef<string>("");

  const { data: fromAsset } = useQuery<{ id: string; title: string; type: string; content: string }>({
    queryKey: ["wa-from-asset", fromAssetId],
    queryFn: () => api(`/content-hub/assets/${fromAssetId}`),
    enabled: !!fromAssetId,
  });

  useEffect(() => {
    if (fromAsset?.content && prefilledRef.current !== fromAsset.id) {
      prefilledRef.current = fromAsset.id;
      setMessage(fromAsset.content);
      setAssetNotice(`Message loaded from Content Hub: "${fromAsset.title}"`);
    }
  }, [fromAsset]);

  async function onPickMedia(e: React.ChangeEvent<HTMLInputElement>) {
    const file = e.target.files?.[0];
    e.target.value = ""; // allow re-picking the same file
    if (!file) return;
    if (file.size > 16 * 1024 * 1024) {
      setLastRunNotice("Attachment too large (max 16MB).");
      return;
    }
    const base64 = await fileToBase64(file);
    setMedia({ base64, mimetype: file.type || "application/octet-stream", filename: file.name });
  }

  // Pipeline stage picker → lets the user pull recipients directly from CRM.
  const { data: stages = [] } = useQuery<PipelineStage[]>({
    queryKey: ["stages"],
    queryFn: () => api("/pipeline/stages"),
  });

  // Preview how many leads in the chosen stage actually have a phone number,
  // so the user knows what they're about to send to.
  const { data: stageLeads = [] } = useQuery<LeadLite[]>({
    queryKey: ["wa-stage-leads", stageId],
    queryFn: async () => {
      if (!stageId) return [];
      const rows = await api<{ rows?: LeadLite[] } | LeadLite[]>(
        `/leads?stage_id=${stageId}&limit=500`
      );
      return Array.isArray(rows) ? rows : rows.rows || [];
    },
    enabled: !!stageId,
  });

  const recipientCount = stageLeads.filter(
    (l) => (l.phone || "").trim() !== ""
  ).length;

  const startCampaign = useMutation({
    mutationFn: () =>
      api<{ id: string }>("/whatsapp-web/campaigns/start", {
        method: "POST",
        body: {
          account_id: accountId || undefined,
          message,
          media: media || undefined,
          stage_id: stageId || undefined,
          delay_min: Math.max(3, delayMin) * 1000,
          delay_max: Math.max(6, delayMax) * 1000,
          country_code: countryCode,
        },
      }),
    onSuccess: (r) => {
      setLastRunNotice(`Campaign queued (${r.id.slice(0, 8)}…)`);
      qc.invalidateQueries({ queryKey: ["wa-campaigns"] });
    },
    onError: (e) =>
      setLastRunNotice(
        e instanceof ApiError ? `Failed: ${e.message}` : "Failed to start"
      ),
  });

  // ── Campaign list + live progress ─────────────────────────────────────
  const { data: campaigns = [] } = useQuery<WaCampaign[]>({
    queryKey: ["wa-campaigns"],
    queryFn: () => api("/whatsapp-web/campaigns"),
    refetchInterval: 4000,
  });

  const readyAccount = accounts.find((a) => a.status === "ready");
  const canSend = !!readyAccount;
  const readyAccounts = accounts.filter((a) => a.status === "ready");

  // ── Inbox (incoming replies) ──────────────────────────────────────────
  const [inboxAccountId, setInboxAccountId] = useState<string>("");
  const [openPhone, setOpenPhone] = useState<string>("");
  const [reply, setReply] = useState<string>("");

  const inboxQs = inboxAccountId ? `?account_id=${inboxAccountId}` : "";

  const { data: chats = [] } = useQuery<WaChat[]>({
    queryKey: ["wa-chats", inboxAccountId],
    queryFn: () => api(`/whatsapp-web/chats${inboxQs}`),
    enabled: canSend,
    refetchInterval: 5000,
  });

  const { data: thread } = useQuery<{ chat: WaChat | null; messages: WaMessage[] }>({
    queryKey: ["wa-thread", inboxAccountId, openPhone],
    queryFn: () => api(`/whatsapp-web/chats/${openPhone}${inboxQs}`),
    enabled: !!openPhone && canSend,
    refetchInterval: 4000,
  });

  const sendReply = useMutation({
    mutationFn: () =>
      api("/whatsapp-web/send", {
        method: "POST",
        body: { account_id: inboxAccountId || undefined, phone: openPhone, message: reply },
      }),
    onSuccess: () => {
      setReply("");
      qc.invalidateQueries({ queryKey: ["wa-thread", inboxAccountId, openPhone] });
      qc.invalidateQueries({ queryKey: ["wa-chats", inboxAccountId] });
    },
  });

  return (
    <div className="mx-auto max-w-6xl space-y-6 p-6">
      {/* Page header ---------------------------------------------------- */}
      <div className="flex items-center justify-between">
        <div>
          <h1 className="flex items-center gap-2 text-2xl font-bold text-slate-900">
            <MessageCircle className="h-6 w-6 text-emerald-600" />
            WhatsApp Outreach
          </h1>
          <p className="mt-1 text-sm text-slate-500">
            Pair your WhatsApp by scanning the QR — then send personalised
            messages to leads pulled straight from the pipeline.
          </p>
        </div>
      </div>

      {/* Accounts (QR section) — self-contained, independent of the campaign API */}
      <section className="rounded-xl border border-slate-200 bg-white shadow-sm">
        <header className="flex items-center justify-between border-b border-slate-100 px-5 py-4">
          <div className="flex items-center gap-2">
            <Smartphone className="h-4 w-4 text-slate-500" />
            <h2 className="text-sm font-semibold text-slate-900">
              Connected numbers ({accounts.length}/5)
            </h2>
          </div>
          <button
            onClick={() => addAccount.mutate(`Account ${accounts.length + 1}`)}
            disabled={addAccount.isPending || accounts.length >= 5 || sidecarUnavailable}
            className="inline-flex items-center gap-1.5 rounded-md bg-emerald-600 px-3 py-1.5 text-sm font-medium text-white hover:bg-emerald-700 disabled:opacity-50"
          >
            {addAccount.isPending ? (
              <Loader2 className="h-3.5 w-3.5 animate-spin" />
            ) : (
              <Plus className="h-3.5 w-3.5" />
            )}
            Add number
          </button>
        </header>

        {sidecarUnavailable && (
          <div className="border-b border-amber-100 bg-amber-50 px-5 py-3 text-xs text-amber-900">
            <div className="flex items-start gap-2">
              <AlertCircle className="mt-0.5 h-3.5 w-3.5 flex-shrink-0" />
              <p>
                <span className="font-semibold">QR pairing unavailable.</span>{" "}
                The WhatsApp sidecar service isn&apos;t running/reachable. Deploy
                the <code className="rounded bg-amber-100 px-1">leadcaptura-whatsapp</code>{" "}
                service on Render, then set{" "}
                <code className="rounded bg-amber-100 px-1">WA_SIDECAR_URL</code> +{" "}
                <code className="rounded bg-amber-100 px-1">WA_SIDECAR_TOKEN</code>{" "}
                on the API (token must match the sidecar).
                {sidecarErrorDetail ? (
                  <span className="mt-1 block text-amber-700">Detail: {sidecarErrorDetail}</span>
                ) : null}
              </p>
            </div>
          </div>
        )}

        {accounts.length === 0 && !sidecarUnavailable && (
          <div className="p-10 text-center text-sm text-slate-500">
            No WhatsApp numbers connected yet. Click <b>Add number</b> to start
            pairing — a QR code will appear here.
          </div>
        )}

        <div className="grid gap-4 p-5 md:grid-cols-2 xl:grid-cols-3">
          {accounts.map((acc) => {
            const badge = STATUS_BADGE[acc.status] || STATUS_BADGE.disconnected;
            return (
              <div
                key={acc.id}
                className="flex flex-col gap-3 rounded-lg border border-slate-200 p-4"
              >
                <div className="flex items-start justify-between gap-2">
                  <div className="min-w-0">
                    <p className="truncate text-sm font-semibold text-slate-900">
                      {acc.label}
                    </p>
                    <p className="mt-0.5 truncate text-xs text-slate-500">
                      {acc.phone ? `+${acc.phone}` : "No phone paired yet"}
                      {acc.pushName ? ` · ${acc.pushName}` : ""}
                    </p>
                  </div>
                  <span
                    className="flex-shrink-0 rounded-full px-2 py-0.5 text-[11px] font-semibold uppercase tracking-wide"
                    style={{ background: badge.bg, color: badge.text }}
                  >
                    {badge.label}
                  </span>
                </div>

                {/* QR or status placeholder ---------------------------- */}
                {acc.status === "qr" && acc.qrDataUrl && (
                  <div className="rounded-md bg-slate-50 p-3 text-center">
                    {/* eslint-disable-next-line @next/next/no-img-element */}
                    <img
                      src={acc.qrDataUrl}
                      alt="Scan with WhatsApp"
                      className="mx-auto h-48 w-48"
                    />
                    <p className="mt-2 text-xs text-slate-600">
                      Open WhatsApp → <b>Linked Devices</b> → Scan
                    </p>
                  </div>
                )}
                {acc.status === "connecting" && (
                  <div className="flex h-48 items-center justify-center rounded-md bg-slate-50 text-sm text-slate-500">
                    <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                    Connecting…
                  </div>
                )}
                {acc.status === "ready" && (
                  <div className="flex h-24 items-center justify-center rounded-md bg-emerald-50 text-sm font-medium text-emerald-700">
                    <CheckCircle2 className="mr-2 h-5 w-5" />
                    Ready to send
                  </div>
                )}
                {acc.status === "disconnected" && (
                  <div className="flex h-24 items-center justify-center rounded-md bg-slate-50 text-sm text-slate-500">
                    Session ended — click reconnect for a new QR.
                  </div>
                )}

                <div className="flex flex-wrap gap-2 border-t border-slate-100 pt-3">
                  <button
                    onClick={() => reconnect.mutate(acc.id)}
                    className="inline-flex items-center gap-1 rounded-md border border-slate-200 px-2 py-1 text-xs text-slate-600 hover:bg-slate-50"
                  >
                    <RefreshCcw className="h-3 w-3" />
                    Reconnect
                  </button>
                  {acc.status === "ready" && (
                    <button
                      onClick={() => logout.mutate(acc.id)}
                      className="inline-flex items-center gap-1 rounded-md border border-slate-200 px-2 py-1 text-xs text-slate-600 hover:bg-slate-50"
                    >
                      <LogOut className="h-3 w-3" />
                      Logout
                    </button>
                  )}
                  <button
                    onClick={() => {
                      if (confirm(`Remove ${acc.label}?`)) removeAccount.mutate(acc.id);
                    }}
                    className="ml-auto inline-flex items-center gap-1 rounded-md border border-red-200 px-2 py-1 text-xs text-red-600 hover:bg-red-50"
                  >
                    Remove
                  </button>
                </div>
              </div>
            );
          })}
        </div>
      </section>

      {/* Composer (campaign API section) — independent of the QR pairing above */}
      <section className="rounded-xl border border-slate-200 bg-white shadow-sm">
        <header className="flex items-center justify-between border-b border-slate-100 px-5 py-4">
          <div className="flex items-center gap-2">
            <Send className="h-4 w-4 text-slate-500" />
            <h2 className="text-sm font-semibold text-slate-900">
              Bulk WhatsApp campaign
            </h2>
          </div>
        </header>

        {assetNotice && (
          <div className="flex items-center gap-2 border-b border-emerald-100 bg-emerald-50 px-5 py-2.5 text-xs text-emerald-800">
            <FolderOpen className="h-3.5 w-3.5 flex-shrink-0" />
            <span>{assetNotice}</span>
            <span className="text-emerald-500">— edit it below, attach a product image, then pick recipients.</span>
          </div>
        )}

        {sidecarUnavailable && (
          <div className="border-b border-amber-100 bg-amber-50 px-5 py-3 text-xs text-amber-900">
            <div className="flex items-start gap-2">
              <AlertCircle className="mt-0.5 h-3.5 w-3.5 flex-shrink-0" />
              <p>
                <span className="font-semibold">Campaign API offline.</span>{" "}
                Bulk sends are routed through the backend campaign endpoint,
                which currently can&apos;t reach the WhatsApp sidecar. You can
                still draft a message — sending will become available once the
                sidecar is provisioned.
              </p>
            </div>
          </div>
        )}

        <div className="grid gap-4 p-5 md:grid-cols-2">
          {/* LEFT: settings */}
          <div className="space-y-4">
            <label className="block text-sm">
              <span className="text-xs font-medium text-slate-700">
                Send from
              </span>
              <select
                value={accountId}
                onChange={(e) => setAccountId(e.target.value)}
                className="mt-1 block w-full rounded-md border border-slate-300 px-3 py-2 text-sm"
              >
                <option value="">
                  {readyAccount
                    ? `Default — ${readyAccount.label} (+${readyAccount.phone})`
                    : "No account ready yet"}
                </option>
                {accounts
                  .filter((a) => a.status === "ready")
                  .map((a) => (
                    <option key={a.id} value={a.id}>
                      {a.label} {a.phone ? `(+${a.phone})` : ""}
                    </option>
                  ))}
              </select>
            </label>

            <label className="block text-sm">
              <span className="text-xs font-medium text-slate-700">
                Recipients — pipeline stage
              </span>
              <select
                value={stageId}
                onChange={(e) => setStageId(e.target.value)}
                className="mt-1 block w-full rounded-md border border-slate-300 px-3 py-2 text-sm"
              >
                <option value="">— pick a stage —</option>
                {stages.map((s) => (
                  <option key={s.id} value={s.id}>
                    {s.name}
                  </option>
                ))}
              </select>
              {stageId && (
                <p className="mt-1.5 flex items-center gap-1 text-xs text-slate-500">
                  <Users className="h-3 w-3" />
                  {recipientCount} lead{recipientCount === 1 ? "" : "s"} with a phone
                  number{" "}
                  {stageLeads.length - recipientCount > 0 &&
                    `(${stageLeads.length - recipientCount} skipped, no phone)`}
                </p>
              )}
            </label>

            <div className="grid grid-cols-3 gap-3">
              <label className="block text-sm">
                <span className="text-xs font-medium text-slate-700">
                  Country code
                </span>
                <input
                  value={countryCode}
                  onChange={(e) => setCountryCode(e.target.value)}
                  className="mt-1 block w-full rounded-md border border-slate-300 px-3 py-2 text-sm"
                  placeholder="91"
                />
              </label>
              <label className="block text-sm">
                <span className="text-xs font-medium text-slate-700">
                  Min delay (s)
                </span>
                <input
                  type="number"
                  min={3}
                  value={delayMin}
                  onChange={(e) => setDelayMin(Number(e.target.value) || 5)}
                  className="mt-1 block w-full rounded-md border border-slate-300 px-3 py-2 text-sm"
                />
              </label>
              <label className="block text-sm">
                <span className="text-xs font-medium text-slate-700">
                  Max delay (s)
                </span>
                <input
                  type="number"
                  min={6}
                  value={delayMax}
                  onChange={(e) => setDelayMax(Number(e.target.value) || 12)}
                  className="mt-1 block w-full rounded-md border border-slate-300 px-3 py-2 text-sm"
                />
              </label>
            </div>
          </div>

          {/* RIGHT: message body + tokens */}
          <div>
            <label className="block text-sm">
              <span className="text-xs font-medium text-slate-700">
                Message
              </span>
              <textarea
                value={message}
                onChange={(e) => setMessage(e.target.value)}
                rows={9}
                className="mt-1 block w-full resize-y rounded-md border border-slate-300 px-3 py-2 font-mono text-sm"
                placeholder="Hi {first_name}, I noticed you're at {company} — wanted to share something that might help your team…"
              />
            </label>
            <p className="mt-1.5 text-xs text-slate-500">
              Tokens:{" "}
              {["{first_name}", "{full_name}", "{company}", "{title}", "{email}"].map(
                (t) => (
                  <code
                    key={t}
                    className="mr-1 rounded bg-slate-100 px-1.5 py-0.5"
                  >
                    {t}
                  </code>
                )
              )}
            </p>

            {/* Attachment — image / video / PDF sent with the text as caption */}
            <div className="mt-3">
              {media ? (
                <div className="flex items-center gap-2 rounded-md border border-emerald-200 bg-emerald-50 px-3 py-2 text-xs text-emerald-800">
                  <Paperclip className="h-3.5 w-3.5 flex-shrink-0" />
                  <span className="truncate">{media.filename}</span>
                  <span className="text-emerald-500">
                    ({Math.round((media.base64.length * 0.75) / 1024)} KB)
                  </span>
                  <button
                    onClick={() => setMedia(null)}
                    className="ml-auto rounded p-0.5 hover:bg-emerald-100"
                    title="Remove attachment"
                  >
                    <X className="h-3.5 w-3.5" />
                  </button>
                </div>
              ) : (
                <label className="inline-flex cursor-pointer items-center gap-1.5 rounded-md border border-slate-200 px-3 py-1.5 text-xs font-medium text-slate-600 hover:bg-slate-50">
                  <Paperclip className="h-3.5 w-3.5" />
                  Attach image / video / PDF
                  <input
                    type="file"
                    accept="image/*,video/*,application/pdf"
                    onChange={onPickMedia}
                    className="hidden"
                  />
                </label>
              )}
              {media && (
                <p className="mt-1 text-[11px] text-slate-400">
                  The message above is sent as the caption on this attachment.
                </p>
              )}
            </div>
          </div>
        </div>

        <div className="flex items-center justify-between border-t border-slate-100 px-5 py-4">
          <p className="text-xs text-slate-500">
            {!canSend
              ? "Pair a WhatsApp number above before sending."
              : `Will send from +${readyAccount?.phone || "—"} with a ${delayMin}–${delayMax}s gap between messages.`}
          </p>
          <div className="flex items-center gap-3">
            {lastRunNotice && (
              <span className="text-xs text-slate-500">{lastRunNotice}</span>
            )}
            <button
              onClick={() => startCampaign.mutate()}
              disabled={
                !canSend ||
                startCampaign.isPending ||
                (!message.trim() && !media) ||
                !stageId
              }
              className="inline-flex items-center gap-1.5 rounded-md bg-emerald-600 px-4 py-2 text-sm font-semibold text-white hover:bg-emerald-700 disabled:opacity-50"
            >
              {startCampaign.isPending ? (
                <Loader2 className="h-4 w-4 animate-spin" />
              ) : (
                <Send className="h-4 w-4" />
              )}
              Start campaign
            </button>
          </div>
        </div>
      </section>

      {/* Inbox — incoming replies + reply box --------------------------- */}
      <section className="rounded-xl border border-slate-200 bg-white shadow-sm">
        <header className="flex items-center justify-between border-b border-slate-100 px-5 py-4">
          <div className="flex items-center gap-2">
            <InboxIcon className="h-4 w-4 text-slate-500" />
            <h2 className="text-sm font-semibold text-slate-900">Inbox — replies</h2>
          </div>
          {readyAccounts.length > 1 && (
            <select
              value={inboxAccountId}
              onChange={(e) => {
                setInboxAccountId(e.target.value);
                setOpenPhone("");
              }}
              className="rounded-md border border-slate-300 px-2 py-1 text-xs"
            >
              <option value="">Default account</option>
              {readyAccounts.map((a) => (
                <option key={a.id} value={a.id}>
                  {a.label}
                </option>
              ))}
            </select>
          )}
        </header>

        {!canSend ? (
          <div className="p-10 text-center text-sm text-slate-500">
            Pair a WhatsApp number above to see replies here.
          </div>
        ) : (
          <div className="grid grid-cols-1 divide-y divide-slate-100 md:grid-cols-[270px_1fr] md:divide-x md:divide-y-0">
            {/* Conversation list */}
            <div className="max-h-[460px] overflow-y-auto">
              {chats.length === 0 ? (
                <div className="p-6 text-center text-xs text-slate-400">
                  No conversations yet. Replies from people you message will
                  appear here.
                </div>
              ) : (
                chats.map((ch) => {
                  const active = ch.phone === openPhone;
                  return (
                    <button
                      key={ch.phone}
                      onClick={() => setOpenPhone(ch.phone)}
                      className={`flex w-full items-start gap-2 border-b border-slate-50 px-4 py-3 text-left hover:bg-slate-50 ${
                        active ? "bg-emerald-50" : ""
                      }`}
                    >
                      <div className="min-w-0 flex-1">
                        <div className="flex items-center justify-between gap-2">
                          <p className="truncate text-sm font-medium text-slate-900">
                            {ch.name || `+${ch.phone}`}
                          </p>
                          {ch.unreadCount > 0 && (
                            <span className="flex-shrink-0 rounded-full bg-emerald-600 px-1.5 py-0.5 text-[10px] font-semibold text-white">
                              {ch.unreadCount}
                            </span>
                          )}
                        </div>
                        <p className="mt-0.5 truncate text-xs text-slate-500">
                          {ch.fromMe ? "You: " : ""}
                          {ch.lastMessage || "—"}
                        </p>
                      </div>
                    </button>
                  );
                })
              )}
            </div>

            {/* Thread + reply */}
            <div className="flex max-h-[460px] flex-col">
              {!openPhone ? (
                <div className="flex flex-1 items-center justify-center p-10 text-sm text-slate-400">
                  Select a conversation to read + reply.
                </div>
              ) : (
                <>
                  <div className="flex-1 space-y-2 overflow-y-auto bg-slate-50 p-4">
                    {(thread?.messages || []).length === 0 ? (
                      <div className="py-8 text-center text-xs text-slate-400">
                        No messages loaded yet.
                      </div>
                    ) : (
                      (thread?.messages || []).map((m) => (
                        <div
                          key={m.id}
                          className={`flex ${m.fromMe ? "justify-end" : "justify-start"}`}
                        >
                          <div
                            className={`max-w-[75%] rounded-lg px-3 py-2 text-sm ${
                              m.fromMe
                                ? "bg-emerald-600 text-white"
                                : "border border-slate-200 bg-white text-slate-800"
                            }`}
                          >
                            {m.text || (
                              <span className="italic opacity-70">[{m.type}]</span>
                            )}
                            <div
                              className={`mt-0.5 text-[10px] ${
                                m.fromMe ? "text-emerald-100" : "text-slate-400"
                              }`}
                            >
                              {new Date(m.timestamp).toLocaleString()}
                            </div>
                          </div>
                        </div>
                      ))
                    )}
                  </div>
                  <div className="flex items-center gap-2 border-t border-slate-100 p-3">
                    <input
                      value={reply}
                      onChange={(e) => setReply(e.target.value)}
                      onKeyDown={(e) => {
                        if (e.key === "Enter" && !e.shiftKey && reply.trim()) {
                          e.preventDefault();
                          sendReply.mutate();
                        }
                      }}
                      placeholder="Type a reply…"
                      className="flex-1 rounded-md border border-slate-300 px-3 py-2 text-sm"
                    />
                    <button
                      onClick={() => sendReply.mutate()}
                      disabled={!reply.trim() || sendReply.isPending}
                      className="inline-flex items-center gap-1.5 rounded-md bg-emerald-600 px-3 py-2 text-sm font-semibold text-white hover:bg-emerald-700 disabled:opacity-50"
                    >
                      {sendReply.isPending ? (
                        <Loader2 className="h-4 w-4 animate-spin" />
                      ) : (
                        <Send className="h-4 w-4" />
                      )}
                    </button>
                  </div>
                </>
              )}
            </div>
          </div>
        )}
      </section>

      {/* Campaign history ----------------------------------------------- */}
      <section className="rounded-xl border border-slate-200 bg-white shadow-sm">
        <header className="border-b border-slate-100 px-5 py-4">
          <h2 className="text-sm font-semibold text-slate-900">
            Recent campaigns
          </h2>
        </header>
        {campaigns.length === 0 ? (
          <div className="p-10 text-center text-sm text-slate-500">
            Your past WhatsApp campaigns will appear here.
          </div>
        ) : (
          <ul className="divide-y divide-slate-100">
            {campaigns.map((c) => {
              const pct = c.stats.total
                ? Math.round((c.stats.processed / c.stats.total) * 100)
                : 0;
              const badge = CAMP_BADGE[c.status] || CAMP_BADGE.queued;
              return (
                <li key={c.id} className="p-5">
                  <div className="flex items-start justify-between gap-3">
                    <div className="min-w-0">
                      <p className="truncate text-sm font-medium text-slate-900">
                        {c.message.slice(0, 90)}
                        {c.message.length > 90 ? "…" : ""}
                      </p>
                      <p className="mt-1 text-xs text-slate-500">
                        {new Date(c.createdAt).toLocaleString()} ·{" "}
                        {c.stats.sent} sent · {c.stats.failed} failed
                      </p>
                    </div>
                    <div className="flex items-center gap-2">
                      <span
                        className="rounded-full px-2 py-0.5 text-[11px] font-semibold uppercase tracking-wide"
                        style={{ background: badge.bg, color: badge.text }}
                      >
                        {c.status}
                      </span>
                      {c.status === "running" && (
                        <button
                          onClick={() =>
                            api(`/whatsapp-web/campaigns/${c.id}/pause`, {
                              method: "POST",
                            }).then(() =>
                              qc.invalidateQueries({ queryKey: ["wa-campaigns"] })
                            )
                          }
                          className="rounded-md border border-slate-200 p-1 text-slate-600 hover:bg-slate-50"
                          title="Pause"
                        >
                          <Pause className="h-3.5 w-3.5" />
                        </button>
                      )}
                      {c.status === "paused" && (
                        <button
                          onClick={() =>
                            api(`/whatsapp-web/campaigns/${c.id}/resume`, {
                              method: "POST",
                            }).then(() =>
                              qc.invalidateQueries({ queryKey: ["wa-campaigns"] })
                            )
                          }
                          className="rounded-md border border-slate-200 p-1 text-slate-600 hover:bg-slate-50"
                          title="Resume"
                        >
                          <Play className="h-3.5 w-3.5" />
                        </button>
                      )}
                    </div>
                  </div>
                  <div className="mt-3">
                    <div className="h-1.5 w-full overflow-hidden rounded-full bg-slate-100">
                      <div
                        className="h-full bg-emerald-500 transition-all"
                        style={{ width: `${pct}%` }}
                      />
                    </div>
                    <p className="mt-1 text-xs text-slate-500">
                      {c.stats.processed}/{c.stats.total} processed ({pct}%)
                    </p>
                  </div>
                </li>
              );
            })}
          </ul>
        )}
      </section>
    </div>
  );
}
